assignment7/config/routes.rb
Rails.application.routes.draw do
  resources :todos
end

assignment7/app/models/todo.rb
class Todo < ActiveRecord::Base
end

assignment7/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

assignment7/app/controllers/todos_controller.rb
class TodoController < ApplicationController
def index
	@todos = Todo.all
end

def new
	@todo = Todo.new
end

def create
  @todo = Todo.create(todo_params)
  redirect_to '/todo'
end

private
def todo_params
  params.require(:todo).permit(:item)
end

  def edit
  @todo = Todo.find(params[:id])
end

def update
  @todo = Todo.find(params[:id]) 
  @todo.update
  end

  def destroy
  @todo = Todo.find(params[:id])
  @todo.destroy
end
end

assignment7/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment7/app/helpers/todos_helper.rb
module TodosHelper
end

assignment7/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

assignment7/app/views/todos/edit.html.slim
h2 Edit todo
= form_for(@link) do |f|
  = f.text_field :item
  = f.submit

  - @todos.each do |todo|
  ul
    li = todo.item
p
  = link_to "New", new_todo_path
p
  = link_to "Edit", edit_todo_path
p
  = link_to "Delete", '#'

assignment7/app/views/todos/index.html.slim
- @todos.each do |todo|
	ul
		li = todo.item

p = link_to "New", '#'
p = link_to "Edit", '#'
p = link_to "Delete", '#'

assignment7/app/views/todos/new.html.slim
= form_for(@todo) do |f|
  p
    = f.text_field :item, :placeholder => "Add new item"
  p
    = f.submit

    - @todos.each do |todo|
  ul
    li = todo.item
p
  = link_to "New", new_todo_path
p
  = link_to "Edit", '#'
p
  = link_to "Delete", '#'